name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      -   uses: actions/checkout@v4

      -   name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'adopt'

      -   name: Login to Dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      -   name: Cache local Maven repository
          uses: actions/cache@v4
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      -   name: Maven Build, Test, and Create Docker Image
          run: |
            mvn clean install -Dmaven.test.skip=true
            mvn spring-boot:build-image -Dspring-boot.build-image.imageName=mansero/catalog:0.0.1-SNAPSHOT -Dspring.profiles.active=h2
            docker push mansero/catalog:0.0.1-SNAPSHOT
      -   name: Jacoco Code Coverage report
          run: |
            mvn jacoco:report
      -   name: Upload JaCoCo Report
          uses: actions/upload-artifact@v3
          with:
            name: jacoco-report
            path: target/site/jacoco
                    - name: Publish JaCoCo Report to GitHub Pages
                    run: |
                      git config --global user.name "github-actions[bot]"
                      git config --global user.email "github-actions[bot]@users.noreply.github.com"
                      mkdir -p out && cp -r target/site/jacoco/* out/
                      git init
                      git checkout -b gh-pages
                      git add out/*
                      git commit -m "Publish JaCoCo Report"
                      git remote add origin https://github.com/${{ github.repository }}.git
                      git push --force origin gh-pages

      -   name: Display build status
          run: echo "Build completed successfully"